# Generated by Django 5.0.14 on 2026-02-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
