# Generated by Django 5.0.14 on 2026-02-26 15:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='interes_total_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si defines este valor, se usará en lugar de calcular por porcentaje', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Interés Total ($)'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Tasa de Interés Mensual (%)'),
        ),
    ]
