# Generated by Django 5.0.14 on 2026-02-26 15:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_prestamo_interes_total_fijo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='monto_interes_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Define el monto mensual a cobrar como interés. El porcentaje se calculará automáticamente', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto Interés Mensual ($)'),
        ),
    ]
