# Generated by Django 5.0.14 on 2026-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_prestamo_monto_interes_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono 2'),
        ),
    ]
