# Generated by Django 5.0.14 on 2026-03-05 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_add_parcial_estado_cuota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='cobrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Cobrador'),
        ),
    ]
